version: '3.7'
services:
  starter-server:
    container_name: starter-server
    environment: 
      - NODE_ENV=production
    env_file:
      - .env
    build:
      context: ./
    image: starter-server
    ports:
     - "5000:5000"
    networks:
      - app-network 

networks:    
  app-network:
    external: true